First commit
KisiMissi/employee-cards pull request #1
Opened 2023-07-03 01:10 UTC by KisiMissi

2023-07-15 12:14 UTC, progressicu requested changes

2023-07-15 12:14 UTC, progressicu commented on src/main/java/org/kaoden/Main.java
> +            System.out.println(dataFilePath);
зачем в sout писать это?

2023-07-15 12:14 UTC, progressicu commented on src/main/java/org/kaoden/module/Employee.java
> +    public Employee setFirstName(String firstName) {
зачем тебе такой метод? 
1. Чем не устроил сеттер от lombok
2. Если даже что-то не так в этом сеттере, то зачем через Employee.this.firstName?

2023-07-15 12:14 UTC, progressicu commented on src/test/java/org/kaoden/FileHandlerTest.java
> +        tempDir = Files.createTempDirectory(null);
разберись получше как работает @TempDir. Тебе там не надо ничего вручную создавать

2023-07-15 12:14 UTC, progressicu commented on src/test/java/org/kaoden/FileHandlerTest.java
> +        Path tempFile = tempDir.resolve("employeeValid.txt");
где комменты Arrange, Act, Assert?

2023-07-15 12:14 UTC, progressicu commented on src/main/java/org/kaoden/module/Employee.java
> +    public int compareTo(Employee o) {
зачем тебе это, если он нигде не используется?

2023-07-15 12:14 UTC, progressicu commented on src/main/java/org/kaoden/module/Employee.java
> +                "ФИО: " + firstName + " " + lastName + "\n" +
Написано ФИО, а выводишь только ФИ

2023-07-15 12:14 UTC, progressicu commented on src/main/java/org/kaoden/module/Post.java
> +public record Post(UUID uuid, String postName) {
зачем называть в классе Post поле postName. Почему не просто name?

2023-07-15 12:14 UTC, progressicu commented on src/main/java/org/kaoden/Main.java
> +        return matcher.find() ? matcher.group("filePath") : "";
допустим условие не выполнилось и из метода вернулось "". Что тогда случится дальше? Если я правильно понимаю, то будет ошибка

2023-07-15 12:14 UTC, progressicu commented on src/main/java/org/kaoden/Main.java
> +            LOGGER.error("File not found", ex);
почему ты тут пишешь в лог, что файл не найден, если по факту ты отлавливаешь просто IOException, которая не всегда будет означать что файла нету

2023-07-15 12:14 UTC, progressicu commented on src/main/java/org/kaoden/Main.java
> +        List<Employee> employeeList;
если у тебя всё внутри try-catch, то зачем это вынес?

2023-07-15 12:14 UTC, progressicu commented on src/main/java/org/kaoden/FileHandler.java
> +        BufferedReader bufferedReader = new BufferedReader(
try with resources надо использовать. Когда работаешь с ресурсами (соединение к бд/сайту/..., файлы, ...) не забывай, что нужно правильно открывать, закрывать их и обрабатывать различные исключения

2023-07-15 12:14 UTC, progressicu commented on src/main/java/org/kaoden/FileHandler.java
> +    private static Map<UUID, Post> employeePositions;
зачем вынес это в поле класса?

2023-07-15 12:14 UTC, progressicu commented on src/main/java/org/kaoden/FileHandler.java
> +        while ((line = bufferedReader.readLine()) != null) {
Есть уже много других способов прочитать файл. Используй их.
Можно, например, прочитать весь файл сразу в одну строку, а потом просто разбить её по переносам. Или можно получить Stream<String> и обработать его

2023-07-15 12:14 UTC, progressicu commented on src/main/java/org/kaoden/FileHandler.java
> +                    .post(employeePositions.get(UUID.fromString(matcher.group("postId")))).build();
build на новую строку, чтобы было красивее

2023-07-15 12:14 UTC, progressicu commented on src/main/java/org/kaoden/FileHandler.java
> +        List<String> infoAboutEmployee = readingFileWithEmployees(file);
Можно было не создавать заранее List<Employee> employeeList, а чтобы этот метод именно вернул и ты объявил переменную. Т.е. типа так:
``` java
        List<String> employesAsStrings = readingEmloyeeStringFromFile(file);
        List<Employee> employes = toEmployeeFromString(employesAsStrings);
```

2023-07-15 12:14 UTC, progressicu commented on src/main/java/org/kaoden/FileHandler.java
> +public class FileHandler {
У тебя класс называется FileHandler, а он кроме работы с файлами:
- отвечает за логику преобразования строки в работника
- получает должности работников

Тут лучше переименовать класс во что-то типа ReadEmployeeFromFIle

2023-07-15 12:14 UTC, progressicu commented on src/test/java/org/kaoden/FileHandlerTest.java
> +        Files.writeString(tempFile, "firstName: John\nlastName: Doe\ndescription: A software engineer\ncharacteristics: Hardworking, Intelligent, Dedicated\npostId: 03f6e895-d6c4-4b3c-87db-aa5ddc0e00
Вместо создания каждый раз нового файла во временной директории и написанием лишнего текста в текстах, можно просто создать нужные файлы в тестовых ресурсах и здесь их просто доставать.

Создать какой-нибудь утилитный метод, который по названию файла достанет тебе нужный файл и ты его здесь будешь просто использовать

<img width="1031" alt="изображение" src="https://github.com/KisiMissi/employee-cards/assets/48092349/d11e0428-6522-4e03-8579-881c755786c5">
Например, у нас тоже есть что-то подобное, но только мы не сам файл получаем, а какой-то объект, но внутри метода мы сначала получаем файл и считываем его. Так более удобно и лаконично смотрится, чем всё это в тесте писать, а потом и смотреть

2023-07-15 12:14 UTC, progressicu commented on src/test/java/org/kaoden/FileHandlerTest.java
> +        assertAll(
вместо junit можно (но необязательно в принципе) тестировать через либу assterj используя класс SoftAssertions. Довольно удобно я бы сказал получается. Будет что-то похожее

2023-07-15 12:14 UTC, progressicu commented on src/test/java/org/kaoden/FileHandlerTest.java
> +    public void getEmployeeList_VALID_FILE() throws IOException {
почему в наименование и нижнее подчеркивание и UPPER_CASE?

2023-07-15 12:14 UTC, progressicu commented on src/main/java/org/kaoden/FileHandler.java
> +    public static List<Employee> getEmployeeList(File file) throws IOException {
раз это fileHandler, то по идее он и должен обрабатывать различные IOException, а не прокидывать их выше

2023-07-31 01:24 UTC, KisiMissi commented on src/test/java/org/kaoden/FileHandlerTest.java
> +        Path tempFile = tempDir.resolve("employeeValid.txt");
Разве их обязательно писать? Я читал, что достаточно отделять эти блоки пустой строкой.

2023-07-31 01:43 UTC, KisiMissi commented on src/test/java/org/kaoden/FileHandlerTest.java
> +    public void getEmployeeList_VALID_FILE() throws IOException {
Подскажите тога как лучше называть тестовые методы. Если я тестирую разные случаи работы одного метода, то как правильнее будет их назвать? Может есть какие нибудь правила или условности?

2023-08-12 01:54 UTC, progressicu commented on src/test/java/org/kaoden/FileHandlerTest.java
> +        Path tempFile = tempDir.resolve("employeeValid.txt");
Ты прав, что их можно отделять пустой строкой. Но когда этих пустых строк не одна и тест сложный, то пустыми строками отделяют просто логические блоки в рамках одного блока. Например, в arrange может быть подготовка сначала каких-то объектов, потом подготовка сервера и прочее и всё это отделяется строкой, в таком случае ты запутаешься если AAA блоки будешь разделять пустой строкой, а комменты четко выделяются и их сразу видно

Вот пример теста, где внутри каждого из блоков мы разделяем какие-то логически законченные части тоже пустой строкой
<img width="886" alt="image" src="https://github.com/KisiMissi/employee-cards/assets/48092349/4e198f83-935a-40e1-899d-bd326d8f66ba">

2023-08-12 01:56 UTC, progressicu commented on src/test/java/org/kaoden/FileHandlerTest.java
> +    public void getEmployeeList_VALID_FILE() throws IOException {
Тут несколько вариантов. Либо просто в camelCase всё и писать, например, getEmployeeListValidFile, ...
Или можно использовать nestedClass https://www.baeldung.com/junit-5-nested-test-classes. Называешь класс в соответствие с методом (например), а внутри уже конкретизруешь

2023-08-18 10:59 UTC, progressicu approved these changes

2023-08-18 11:05 UTC, merged